### ISSUE TITLE
[Question] Support for AMP ?

### ISSUE THREAD

**Issue by MankaranSingh** [isaac-sim/IsaacLab#1004]
### Question

Hi, any timeline on when AMP environment would be ported to isaac Lab ?

**Comment by kellyguo11** [comment]
Hello, AMP support is on our roadmap and will hopefully be available in the coming months.

**Comment by OliEfr** [comment]
Hi, I have a working AMP implementation for IsaacLab. I would be willing to open a PR. Is the IsaacLab-Team interested?

**Comment by kellyguo11** [comment]
Hi there, great to hear you have AMP implementation for Isaac Lab! We are planning to put out a few AMP environments in the next few days for SKRL. Would be interesting to see if we can integrate these implementations together to have more RL library support.

**Comment by OliEfr** [comment]
@kellyguo11 I checked your code and saw you implemented it as a direct RL env. I guess because integration in manager based envs might be a bit messy. I, however, implemented in a [manager based env](https://github.com/OliEfr/IsaacLab/blob/5671a8a551cf8d4c8b2dfe751825952aeb26c2f5/source/extensions/omni.isaac.lab/omni/isaac/lab/envs/manager_based_rl_env.py#L79). Also, I implemented AMP in rsl_rl directly and for a quadruped. Let me know if any of that is interesting.

Maybe the [reference state initialization](https://github.com/OliEfr/IsaacLab/blob/5671a8a551cf8d4c8b2dfe751825952aeb26c2f5/source/extensions/omni.isaac.lab/omni/isaac/lab/envs/mdp/events.py#L36) I can be re-used? (I didnt check how you implemented it though)

**Comment by kellyguo11** [comment]
@OliEfr absolutely, would love to have your contribution. Feel free to start a PR and we can discuss how best to integrate the implementations.

**Comment by KingBright** [comment]
Hi there, is there a manager based amp support on the way?

**Comment by OliEfr** [comment]
> Hi there, is there a manager based amp support on the way?

I do have an implementation that I'm willing to share. For general integration in Isaac Lab I think there is still work to be done.

**Comment by ajytak** [comment]
> > Hi there, is there a manager based amp support on the way?
> 
> I do have an implementation that I'm willing to share. For general integration in Isaac Lab I think there is still work to be done.

Hi @OliEfr , it would be great if you could share your implementation for manager-based amp env(link to your repo which implements it), thanks in advance.

**Comment by OliEfr** [comment]
amp ppo: https://github.com/OliEfr/rsl_rl/blob/master/rsl_rl/algorithms/amp_ppo.py
manager based rl env: https://github.com/OliEfr/IsaacLab/blob/add_latent_action_wrapper/source/extensions/omni.isaac.lab/omni/isaac/lab/envs/manager_based_rl_env.py

**Comment by ajytak** [comment]
Thanks a lot!!
