### ISSUE TITLE
Trouble Modifying and Viewing USD files

### ISSUE THREAD

**Issue by StrainFlow** [isaac-sim/IsaacLab#1420]
Hi @Jaraxxus-Me , my issue is not realated to this, but I noticed that you are working with USD files, and I was wondering how you went about modifying and viewing the USD files? I am facing lot of trouble installing Usd by following the instructions in the repo here - https://github.com/PixarAnimationStudios/OpenUSD - if you can point me to any place where you downloaded openusd from that would be super helpful, thanks!

_Originally posted by @meghbhalerao in https://github.com/isaac-sim/IsaacLab/issues/1403#issuecomment-2474284640_

**Comment by meghbhalerao** [comment]
Hi, thanks. 

So I have **managed to install the OpenUSD software** (following instructions here https://github.com/PixarAnimationStudios/OpenUSD, although installing it was very troublesome, it doesnt work with python > 3.10 and doesn't work when I use anaconda python - and this would be ok, but this isn't even mentioned anywhere in the docs nor the install instructions, but in any case). 

And I am able to run the usdcat to cat the usdfiles to the terminal. I also tried some of the vs code extensions, but I am not sure if they work (the vs code extensions that I tried are https://marketplace.visualstudio.com/items?itemName=AnimalLogic.vscode-usda-syntax and https://marketplace.visualstudio.com/items?itemName=sssooonnnggg.usdc-viewer#:~:text=To%20view%20or%20convert%20a,or%20%22Save%20As%20Usda%22.). Maybe I am making some mistake in these extensions, I am not sure? I just add them by installing them using the vs code interface, in the extensions section.

**So my questions are -** 
1. Could you please point me to some resources or help where I can learn about how to view/modify/create usd files to make a custom scene for example (I am very new to usd so I don't really know what the difference is between interactively and procedural making of usd files).

**Some additional context -** 
What I am trying to do is that I have 2 usd models - one is the humanoid and other is the shadow hand, both of which are available in isaac, I am trying to add the hands to the humanoid - so that once I have this I can proceed and do some downstream tasks such as reinfocement learning etc. Since, I do not see a pre-made model of a humanoid with dextrous hands, I need to make it on my own, so that I can make my desired environment. And to do this, I need to modify things at the usd file level, if I understand this correctly.

It would be great to know some thoughts or suggestions on this, thanks!

**Comment by StrainFlow** [comment]
This is a great place to start: 

https://learn.nvidia.com/en-us/training/self-paced-courses

take a look under the "Graphics and Simulation" tab where you'll find a number of intro to OpenUSD courses. 

If you install an Omniverse application like Isaac Sim you should be able to write Omniverse extensions that use the USD APIs in the Omniverse environment. This environment comes with OpenUSD so you shouldn't need to install OpenUSD directly.

**Comment by meghbhalerao** [comment]
Thanks for the suggestions. I will close this issue now.
